---
version: "2.1"
services:
  ipfs:
    image: ipfs/kubo:latest
    container_name: ipfs
    volumes:
      - ./ipfs_staging:/export
      - ./ipfs_data:/data/ipfs
    ports:
      - 4001:4001
      - 5001:5001
      - 8080:8080